### ISSUE TITLE
[Refactor] - Consolidate flexboxgrid.css to sass file

### ISSUE THREAD

**Issue by Sun-Mountain** [BmoreCodeCoffee/bmorecodecoffee.github.io#21]
**Title should be User Story or Short Description of Task -**

**Description and related issues -**

Refactor the flexboxgrid.css file into more compiled sass files.

**What is the goal or purpose of this ticket?**
Originally this site was built in NextJS but that proved to be impossible on an organization github.io repo. After converting it to Vue, the compiled CSS from SASS was compiled.
This will simplify the code and make it easier to find classes.

**Mockups or Screenshots**

### Acceptance criteria

| Given | When | Then |
| ----- | ---- | ---- |
|       |      |      |

### This task is done when…

This could include:

- [ ] a list of changes to be made
- [ ] all acceptance criteria are met
- [ ] the description of what a user might be able to accomplish once this is done
- [ ] identify 508 considerations and/or recommendations

---

**Comment by emanguy** [comment]
I'm not quite sure what this ticket means. Flexbox Grid was a CSS file pulled from this website: http://flexboxgrid.com/, is the intent to refactor it to be templated CSS classes with SASS?
